# Generated by Django 6.0.2 on 2026-03-17 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Rating must be at least 0'), django.core.validators.MaxValueValidator(5, message='Rating cannot be more than 5')]),
        ),
    ]
